;;; go-impl-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from go-impl.el

(autoload 'go-impl "go-impl" "\


(fn RECEIVER INTERFACE)" t)
(register-definition-prefixes "go-impl" '("go-impl-"))

;;; End of scraped data

(provide 'go-impl-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; go-impl-autoloads.el ends here
