;;; go-fill-struct-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from go-fill-struct.el

(autoload 'go-fill-struct "go-fill-struct" "\
Fill go struct at point." t)
(register-definition-prefixes "go-fill-struct" '("go-fill-struct--buf"))

;;; End of scraped data

(provide 'go-fill-struct-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; go-fill-struct-autoloads.el ends here
