;;; electric-operator-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from electric-operator.el

(autoload 'electric-operator-mode "electric-operator" "\
Toggle automatic insertion of spaces around operators (Electric Spacing mode).

With a prefix argument ARG, enable Electric Spacing mode if ARG is
positive, and disable it otherwise.  If called from Lisp, enable
the mode if ARG is omitted or nil.

This is a local minor mode.  When enabled, typing an operator automatically
inserts surrounding spaces, e.g., `=' becomes ` = ',`+=' becomes ` += '.

(fn &optional ARG)" t)
(register-definition-prefixes "electric-operator" '("electric-operator-"))


;;; Generated autoloads from electric-operator-benchmark.el

(register-definition-prefixes "electric-operator-benchmark" '("elp-benchmark" "other-benchmark"))

;;; End of scraped data

(provide 'electric-operator-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; electric-operator-autoloads.el ends here
