;;; evil-major-leader-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from evil-major-leader.el

(autoload 'global-evil-major-leader-mode "evil-major-leader" "\
Global minor mode for <major-leader> support.

This is a minor mode.  If called interactively, toggle the
`Global Evil-Major-Leader mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable
the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `global-evil-major-leader-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(autoload 'evil-major-leader-mode "evil-major-leader" "\
Minor mode to enable <major-leader> support.

This is a minor mode.  If called interactively, toggle the
`Evil-Major-Leader mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable
the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `evil-major-leader-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(autoload 'evil-major-leader/set-leader "evil-major-leader" "\
Set leader key to `key'

(fn KEY)")
(register-definition-prefixes "evil-major-leader" '("evil-major-leader"))

;;; End of scraped data

(provide 'evil-major-leader-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; evil-major-leader-autoloads.el ends here
